"""Add Transaction and PortfolioHistory models

Revision ID: 0fc6672b204f
Revises: 874f825c8e62
Create Date: 2025-12-14 21:45:19.061686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc6672b204f'
down_revision: Union[str, Sequence[str], None] = '874f825c8e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_amount', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
