"""add social features schema

Revision ID: 2194c7f4929f
Revises: 169300a25bcd
Create Date: 2026-01-10 13:50:36.371750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2194c7f4929f'
down_revision: Union[str, Sequence[str], None] = '169300a25bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_shares',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_shares_user_id'), 'portfolio_shares', ['user_id'], unique=False)
    op.add_column('users', sa.Column('is_public_leaderboard', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_public_leaderboard')
    op.drop_index(op.f('ix_portfolio_shares_user_id'), table_name='portfolio_shares')
    op.drop_table('portfolio_shares')
    # ### end Alembic commands ###
