"""add_owner_id_to_transaction_position

Revision ID: 3829df01701c
Revises: 94215eaa8bdb
Create Date: 2025-12-17 23:23:33.253384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3829df01701c'
down_revision: Union[str, Sequence[str], None] = '94215eaa8bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add columns as nullable=True first
    op.add_column('positions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('owner_id', sa.Integer(), nullable=True))

    # 2. Backfill existing data to owner_id=1 (Default User)
    op.execute("UPDATE positions SET owner_id = 1 WHERE owner_id IS NULL")
    op.execute("UPDATE transactions SET owner_id = 1 WHERE owner_id IS NULL")

    # 3. Alter columns to nullable=False
    op.alter_column('positions', 'owner_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('transactions', 'owner_id', existing_type=sa.Integer(), nullable=False)

    # 4. Create indexes and constraints
    op.create_index(op.f('ix_positions_owner_id'), 'positions', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_position_owner_asset', 'positions', ['owner_id', 'asset_id'])
    op.create_foreign_key('fk_positions_owner_id_users', 'positions', 'users', ['owner_id'], ['id'])
    
    op.create_index(op.f('ix_transactions_owner_id'), 'transactions', ['owner_id'], unique=False)
    op.create_foreign_key('fk_transactions_owner_id_users', 'transactions', 'users', ['owner_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_owner_id_users', 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_owner_id'), table_name='transactions')
    op.drop_column('transactions', 'owner_id')
    op.drop_constraint('fk_positions_owner_id_users', 'positions', type_='foreignkey')
    op.drop_constraint('uq_position_owner_asset', 'positions', type_='unique')
    op.drop_index(op.f('ix_positions_owner_id'), table_name='positions')
    op.drop_column('positions', 'owner_id')
    # ### end Alembic commands ###
