"""Add social features: Portfolio visibility, UserFollow, LeaderboardRank

Revision ID: 4135d7ded6fa
Revises: 7e1faf4ea7e5
Create Date: 2026-01-16 23:16:05.302286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4135d7ded6fa'
down_revision: Union[str, Sequence[str], None] = '7e1faf4ea7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Safely create Enum types if they don't exist
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'portfoliovisibility') THEN
                CREATE TYPE portfoliovisibility AS ENUM ('PRIVATE', 'PUBLIC', 'LINK_ONLY');
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'leaderboardperiod') THEN
                CREATE TYPE leaderboardperiod AS ENUM ('DAILY', 'WEEKLY', 'ALL_TIME');
            END IF;
        END$$;
    """)
    
    op.create_table('user_follows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_user_follow')
    )
    op.create_index(op.f('ix_user_follows_follower_id'), 'user_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_follows_following_id'), 'user_follows', ['following_id'], unique=False)
    
    op.create_table('leaderboard_ranks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('period', postgresql.ENUM('DAILY', 'WEEKLY', 'ALL_TIME', name='leaderboardperiod', create_type=False), nullable=False),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_leaderboard_user_period')
    )
    op.create_index(op.f('ix_leaderboard_ranks_period'), 'leaderboard_ranks', ['period'], unique=False)
    op.create_index(op.f('ix_leaderboard_ranks_user_id'), 'leaderboard_ranks', ['user_id'], unique=False)
    
    op.add_column('portfolios', sa.Column('visibility', postgresql.ENUM('PRIVATE', 'PUBLIC', 'LINK_ONLY', name='portfoliovisibility', create_type=False), server_default='PRIVATE', nullable=False))
    op.add_column('portfolios', sa.Column('share_token', sa.Uuid(), nullable=True))
    op.add_column('portfolios', sa.Column('is_primary_for_leaderboard', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_portfolios_share_token'), 'portfolios', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolios_share_token'), table_name='portfolios')
    op.drop_column('portfolios', 'is_primary_for_leaderboard')
    op.drop_column('portfolios', 'share_token')
    op.drop_column('portfolios', 'visibility')
    op.drop_index(op.f('ix_leaderboard_ranks_user_id'), table_name='leaderboard_ranks')
    op.drop_index(op.f('ix_leaderboard_ranks_period'), table_name='leaderboard_ranks')
    op.drop_table('leaderboard_ranks')
    op.drop_index(op.f('ix_user_follows_following_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_follower_id'), table_name='user_follows')
    op.drop_table('user_follows')
    
    # Drop Enum types
    op.execute("DROP TYPE portfoliovisibility")
    op.execute("DROP TYPE leaderboardperiod")
    # ### end Alembic commands ###
