"""remove portfolio_history table

Revision ID: 570b097b62ca
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 11:27:27.926304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '570b097b62ca'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_index(op.f('ix_portfolio_history_timestamp'), table_name='portfolio_history')
    op.drop_table('portfolio_history')
    op.alter_column('assets', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_assets_portfolio_id'), 'assets', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_ranks_user_id'), 'leaderboard_ranks', ['user_id'], unique=False)
    op.create_unique_constraint('uq_leaderboard_user_period', 'leaderboard_ranks', ['user_id', 'period'])
    op.alter_column('notification_settings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=True)
    op.drop_constraint(op.f('fk_notification_settings_user_id_users'), 'notification_settings', type_='foreignkey')
    op.create_foreign_key(None, 'notification_settings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_portfolios_owner_id'), 'portfolios', ['owner_id'], unique=False)
    op.create_index(op.f('ix_positions_asset_id'), 'positions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_unique_constraint('uq_position_portfolio_asset', 'positions', ['portfolio_id', 'asset_id'])
    op.create_index(op.f('ix_transactions_asset_id'), 'transactions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_transactions_portfolio_id'), 'transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_user_follows_follower_id'), 'user_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_user_follows_following_id'), 'user_follows', ['following_id'], unique=False)
    op.create_unique_constraint('uq_user_follow', 'user_follows', ['follower_id', 'following_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_follow', 'user_follows', type_='unique')
    op.drop_index(op.f('ix_user_follows_following_id'), table_name='user_follows')
    op.drop_index(op.f('ix_user_follows_follower_id'), table_name='user_follows')
    op.drop_index(op.f('ix_transactions_portfolio_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_asset_id'), table_name='transactions')
    op.drop_constraint('uq_position_portfolio_asset', 'positions', type_='unique')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_asset_id'), table_name='positions')
    op.drop_index(op.f('ix_portfolios_owner_id'), table_name='portfolios')
    op.drop_constraint(None, 'notification_settings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_notification_settings_user_id_users'), 'notification_settings', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.alter_column('notification_settings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq_leaderboard_user_period', 'leaderboard_ranks', type_='unique')
    op.drop_index(op.f('ix_leaderboard_ranks_user_id'), table_name='leaderboard_ranks')
    op.drop_index(op.f('ix_assets_portfolio_id'), table_name='assets')
    op.alter_column('assets', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assets', 'portfolio_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('portfolio_history',
    sa.Column('total_value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('total_pl', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_portfolio_history_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_history'))
    )
    op.create_index(op.f('ix_portfolio_history_timestamp'), 'portfolio_history', ['timestamp'], unique=False)
    op.create_table('prices',
    sa.Column('value', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_prices_asset_id_assets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices'))
    )
    # ### end Alembic commands ###
