"""Add owner_id to assets and portfolio_history

Revision ID: 94215eaa8bdb
Revises: 0fc6672b204f
Create Date: 2025-12-16 15:32:20.386755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94215eaa8bdb'
down_revision: Union[str, Sequence[str], None] = '0fc6672b204f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'users', ['owner_id'], ['id'])
    op.add_column('portfolio_history', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'portfolio_history', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio_history', type_='foreignkey')
    op.drop_column('portfolio_history', 'owner_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'owner_id')
    # ### end Alembic commands ###
